spring.application.name=opored-scraping

server.port=18082

# Kafka config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=announcementsGroup
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.template.default-topic=announcementsBOE-topic
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Disable Kafka producer logs to avoid excessive noise
logging.level.org.apache.kafka.clients.producer=OFF

spring.http.codecs.max-in-memory-size=500KB